import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  English: {
    home: 'Home',
    aiAssistant: 'AI Assistant',
    govSchemes: 'Government Schemes',
    reportIssue: 'Report Issue',
    complaintTracker: 'Complaint Tracker',
    docAssistant: 'Digital Locker',
    nearbyOffices: 'Nearby Offices',
    emergencyServices: 'Emergency Services',
    profile: 'My Profile',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    dashboard: 'Dashboard',
    logout: 'Logout',
    pendingComplaints: 'Pending Complaints',
    eligibleSchemes: 'Eligible Schemes',
    rewardPoints: 'Reward Points',
    notifications: 'Notifications',
    recentQueries: 'Recent Queries',
    welcomeCitizen: 'Welcome Citizen',
    reportedOn: 'Reported on',
    status: 'Status',
    priority: 'Priority',
    expectedResolution: 'Expected Resolution',
    category: 'Category',
    description: 'Description',
    location: 'Location',
    search: 'Search',
    submit: 'Submit',
    loading: 'Loading...'
  },
  Hindi: {
    home: 'होम',
    aiAssistant: 'एआई सहायक',
    govSchemes: 'सरकारी योजनाएं',
    reportIssue: 'समस्या रिपोर्ट करें',
    complaintTracker: 'शिकायत ट्रैकर',
    docAssistant: 'डिजिटल लॉकर',
    nearbyOffices: 'नज़दीकी कार्यालय',
    emergencyServices: 'आपातकालीन सेवाएं',
    profile: 'मेरी प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    adminPanel: 'प्रशासक पैनल',
    dashboard: 'डैशबोर्ड',
    logout: 'लॉगआउट',
    pendingComplaints: 'लंबित शिकायतें',
    eligibleSchemes: 'योग्य योजनाएं',
    rewardPoints: 'पुरस्कार अंक',
    notifications: 'सूचनाएं',
    recentQueries: 'हाल के प्रश्न',
    welcomeCitizen: 'नागरिक का स्वागत है',
    reportedOn: 'रिपोर्ट की तिथि',
    status: 'स्थिति',
    priority: 'प्राथमिकता',
    expectedResolution: 'अपेक्षित समाधान तिथि',
    category: 'श्रेणी',
    description: 'विवरण',
    location: 'स्थान',
    search: 'खोजें',
    submit: 'जमा करें',
    loading: 'लोड हो रहा है...'
  },
  Tamil: {
    home: 'முகப்பு',
    aiAssistant: 'செயற்கை நுண்ணறிவு உதவியாளர்',
    govSchemes: 'அரசு திட்டங்கள்',
    reportIssue: 'பிரச்சனையை புகார் செய்',
    complaintTracker: 'புகார் கண்காணிப்பு',
    docAssistant: 'டிஜிட்டல் லாக்கர்',
    nearbyOffices: 'அருகிலுள்ள அலுவலகங்கள்',
    emergencyServices: 'அவசர சேவைகள்',
    profile: 'எனது சுயவிவரம்',
    settings: 'அமைப்புகள்',
    adminPanel: 'நிர்வாக குழு',
    dashboard: 'டாஷ்போர்டு',
    logout: 'வெளியேறு',
    pendingComplaints: 'நிலுவையில் உள்ள புகார்கள்',
    eligibleSchemes: 'தகுதியான திட்டங்கள்',
    rewardPoints: 'விருது புள்ளிகள்',
    notifications: 'அறிவிப்புகள்',
    recentQueries: 'சமீபத்திய கேள்விகள்',
    welcomeCitizen: 'வரவேற்கிறோம் குடிமக்களே',
    reportedOn: 'புகார் செய்த தேதி',
    status: 'நிலை',
    priority: 'முன்னுரிமை',
    expectedResolution: 'எதிர்பார்க்கப்படும் தீர்வு',
    category: 'வகை',
    description: 'விளக்கம்',
    location: 'இடம்',
    search: 'தேடு',
    submit: 'சமர்ப்பி',
    loading: 'ஏற்றப்படுகிறது...'
  },
  Telugu: {
    home: 'హోమ్',
    aiAssistant: 'AI సహాయకుడు',
    govSchemes: 'ప్రభుత్వ పథకాలు',
    reportIssue: 'సమస్యను నివేదించండి',
    complaintTracker: 'ఫిర్యాదు ట్రాకర్',
    docAssistant: 'డిజిటల్ లాకర్',
    nearbyOffices: 'సమీప కార్యాలయాలు',
    emergencyServices: 'అవసర సేవలు',
    profile: 'నా ప్రొఫైల్',
    settings: 'సెట్టింగులు',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    dashboard: 'డాష్‌బోర్డ్',
    logout: 'లాగ్ అవుట్',
    pendingComplaints: 'పెండింగ్ ఫిర్యాదులు',
    eligibleSchemes: 'అర్హతగల పథకాలు',
    rewardPoints: 'రివార్డు పాయింట్లు',
    notifications: 'నోటిఫికేషన్లు',
    recentQueries: 'ఇటీవలి ప్రశ్నలు',
    welcomeCitizen: 'సుస్వాగతం పౌరులారా',
    reportedOn: 'నివేదించిన తేదీ',
    status: 'స్థితి',
    priority: 'ప్రాధాన్యత',
    expectedResolution: 'పరిష్కార గడువు',
    category: 'వర్గం',
    description: 'వివరణ',
    location: 'స్థానము',
    search: 'వెతుకుము',
    submit: 'సమర్పించు',
    loading: 'లోడ్ అవుతోంది...'
  },
  Marathi: {
    home: 'होम',
    aiAssistant: 'एआय सहाय्यक',
    govSchemes: 'सरकारी योजना',
    reportIssue: 'समस्या नोंदवा',
    complaintTracker: 'तक्रार ट्रॅकर',
    docAssistant: 'डिजिटल लॉकर',
    nearbyOffices: 'जवळपासची कार्यालये',
    emergencyServices: 'आणीबाणी सेवा',
    profile: 'माझी प्रोफाइल',
    settings: 'सेटिंग्ज',
    adminPanel: 'अॅडमिन पॅनेल',
    dashboard: 'डॅशबोर्ड',
    logout: 'लॉगआउट',
    pendingComplaints: 'प्रलंबित तक्रारी',
    eligibleSchemes: 'पात्र योजना',
    rewardPoints: 'बक्षीस गुण',
    notifications: 'सूचना',
    recentQueries: 'अलीकडील प्रश्न',
    welcomeCitizen: 'नागरिकांचे स्वागत आहे',
    reportedOn: 'तक्रार तारीख',
    status: 'स्थिती',
    priority: 'प्राधान्य',
    expectedResolution: 'अपेक्षित निवारण',
    category: 'वर्ग',
    description: 'वर्णन',
    location: 'स्थान',
    search: 'शोधा',
    submit: 'सादर करा',
    loading: 'लोड होत आहे...'
  },
  Bengali: {
    home: 'হোম',
    aiAssistant: 'এআই সহকারী',
    govSchemes: 'সরকারি প্রকল্পসমূহ',
    reportIssue: 'অভিযোগ নথিভুক্ত করুন',
    complaintTracker: 'অভিযোগ ট্র্যাকার',
    docAssistant: 'ডিজিটাল লকার',
    nearbyOffices: 'নিকটবর্তী কার্যালয়',
    emergencyServices: 'জরুরী সেবাসমূহ',
    profile: 'আমার প্রোফাইল',
    settings: 'সেটিংস',
    adminPanel: 'অ্যাডমিন প্যানেল',
    dashboard: 'ড্যাশবোর্ড',
    logout: 'লগআউট',
    pendingComplaints: 'পেন্ডিং অভিযোগ',
    eligibleSchemes: 'যোগ্য প্রকল্প',
    rewardPoints: 'পুরস্কার পয়েন্ট',
    notifications: 'বিজ্ঞপ্তি',
    recentQueries: 'সাম্প্রতিক প্রশ্নসমূহ',
    welcomeCitizen: 'স্বাগতম নাগরিক',
    reportedOn: 'রিপোর্ট করার তারিখ',
    status: 'অবস্থা',
    priority: 'অগ্রাধিকার',
    expectedResolution: 'সম্ভাব্য সমাধানের তারিখ',
    category: 'বিভাগ',
    description: 'বিবরণ',
    location: 'অবস্থান',
    search: 'অনুসন্ধান করুন',
    submit: 'জমা দিন',
    loading: 'লোড হচ্ছে...'
  },
  Gujarati: {
    home: 'હોમ',
    aiAssistant: 'એઆઈ સહાયક',
    govSchemes: 'સરકારી યોજનાઓ',
    reportIssue: 'સમસ્યા નોંધાવો',
    complaintTracker: 'ફરિયાદ ટ્રેકર',
    docAssistant: 'ડિજિટલ લોકર',
    nearbyOffices: 'નજીકની કચેરીઓ',
    emergencyServices: 'કટોકટી સેવાઓ',
    profile: 'મારી પ્રોફાઇલ',
    settings: 'સેટિંગ્સ',
    adminPanel: 'એડમિન પેનલ',
    dashboard: 'ડેશબોર્ડ',
    logout: 'લોગઆઉટ',
    pendingComplaints: 'બાકી ફરિયાદો',
    eligibleSchemes: 'યોગ્ય યોજનાઓ',
    rewardPoints: 'ઇનામ પોઇન્ટ',
    notifications: 'સૂચનાઓ',
    recentQueries: 'તાજેતરના પ્રશ્નો',
    welcomeCitizen: 'નાગરિકનું સ્વાગત છે',
    reportedOn: 'નોંધાયેલ તારીખ',
    status: 'સ્થિતિ',
    priority: 'પ્રાથમિકતા',
    expectedResolution: 'અપેક્ષિત નિરાકરણ',
    category: 'કેટેગરી',
    description: 'વર્ણન',
    location: 'સ્થળ',
    search: 'શોધો',
    submit: 'સબમિટ કરો',
    loading: 'લોડ થઈ રહ્યું છે...'
  },
  Punjabi: {
    home: 'ਹੋਮ',
    aiAssistant: 'ਏਆਈ ਸਹਾਇਕ',
    govSchemes: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    reportIssue: 'ਸਮੱਸਿਆ ਦਰਜ ਕਰੋ',
    complaintTracker: 'ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕਰ',
    docAssistant: 'ਡਿਜੀਟਲ ਲੌਕਰ',
    nearbyOffices: 'ਨੇੜਲੇ ਦਫਤਰ',
    emergencyServices: 'ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ',
    profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    adminPanel: 'ਐਡਮਿਨ ਪੈਨਲ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    logout: 'ਲੌਗਆਊਟ',
    pendingComplaints: 'ਲੰਬਿਤ ਸ਼ਿਕਾਇਤਾਂ',
    eligibleSchemes: 'ਯੋਗ ਯੋਜਨਾਵਾਂ',
    rewardPoints: 'ਇਨਾਮ ਅੰਕ',
    notifications: 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
    recentQueries: 'ਹਾਲੀਆ ਸਵਾਲ',
    welcomeCitizen: 'ਜੀ ਆਇਆਂ ਨੂੰ ਨਾਗਰਿਕ',
    reportedOn: 'ਦਰਜ ਕਰਨ ਦੀ ਮਿਤੀ',
    status: 'ਸਥਿਤੀ',
    priority: 'ਤਰਜੀਹ',
    expectedResolution: 'ਸੰਭਾਵਿਤ ਹੱਲ',
    category: 'ਸ਼੍ਰੇਣੀ',
    description: 'ਵੇਰਵਾ',
    location: 'ਸਥਾਨ',
    search: 'ਖੋਜੋ',
    submit: 'ਸਬਮਿਟ ਕਰੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('sb_language') || 'English';
  });

  useEffect(() => {
    localStorage.setItem('sb_language', language);
  }, [language]);

  const t = (key) => {
    return (translations[language] && translations[language][key]) || translations['English'][key] || key;
  };

  const languagesList = [
    { code: 'en', name: 'English' },
    { code: 'hi', name: 'Hindi' },
    { code: 'ta', name: 'Tamil' },
    { code: 'te', name: 'Telugu' },
    { code: 'mr', name: 'Marathi' },
    { code: 'bn', name: 'Bengali' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'pa', name: 'Punjabi' }
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languagesList }}>
      {children}
    </LanguageContext.Provider>
  );
};
